### ISSUE TITLE
mp.atan2 returns incorrect results at infinities

### ISSUE THREAD

**Issue by pearu** [mpmath/mpmath#825] opened 2024-07-30 15:31 UTC
As in the title.

Reproducer (using mpmath 1.3):
```python
>>> # (result, expected)
>>> mpmath.mp.atan2(mpmath.inf, mpmath.inf), mpmath.fp.atan2(mpmath.inf, mpmath.inf)
(mpf('nan'), 0.7853981633974483)
>>> mpmath.mp.atan2(-mpmath.inf, mpmath.inf), mpmath.fp.atan2(-mpmath.inf, mpmath.inf)
(mpf('nan'), -0.7853981633974483)
>>> mpmath.mp.atan2(mpmath.inf, -mpmath.inf), mpmath.fp.atan2(mpmath.inf, -mpmath.inf)
(mpf('nan'), 2.356194490192345)
>>> mpmath.mp.atan2(-mpmath.inf, -mpmath.inf), mpmath.fp.atan2(-mpmath.inf, -mpmath.inf)
(mpf('nan'), -2.356194490192345)
```

The expected values are defined per https://en.cppreference.com/w/cpp/numeric/math/atan2

**Comment by skirpichev** [comment] 2024-07-31 02:57
This is a duplicate of #774, fixed in the master by fb035b9 and available in v1.4.0a1.

```pycon
>>> import mpmath
>>> mpmath.__version__
'1.4.0a2.dev46+gfb9e4ae.d20240725'
>>> mpmath.mp.atan2(mpmath.inf, mpmath.inf), mpmath.fp.atan2(mpmath.inf, mpmath.inf)
(mpf('0.78539816339744828'), 0.7853981633974483)
>>> mpmath.mp.atan2(-mpmath.inf, mpmath.inf), mpmath.fp.atan2(-mpmath.inf, mpmath.inf)
(mpf('-0.78539816339744828'), -0.7853981633974483)
>>> mpmath.mp.atan2(mpmath.inf, -mpmath.inf), mpmath.fp.atan2(mpmath.inf, -mpmath.inf)
(mpf('2.3561944901923448'), 2.356194490192345)
>>> mpmath.mp.atan2(-mpmath.inf, -mpmath.inf), mpmath.fp.atan2(-mpmath.inf, -mpmath.inf)
(mpf('-2.3561944901923448'), -2.356194490192345)
```

**Closed by skirpichev** 2024-07-31 02:57 UTC

**Comment by pearu** [comment] 2024-07-31 08:55
Ah, thanks! Sorry for the noise.

**Comment by skirpichev** [comment] 2024-07-31 10:08
You are welcome!

But it's always good to check the development version.  There is a (small) chance, that problem could be already fixed.
