### ISSUE TITLE
mpmath documentation references obsolete gympy instead of gympy2

### ISSUE THREAD

**Issue by yacilus** [mpmath/mpmath#883] opened 2024-10-24 19:27 UTC
In the mpmath documentation on using gympy, it says

"Using gmpy (optional)
By default, mpmath uses Python integers internally. If [gmpy](http://code.google.com/p/gmpy/) version 1.03 or later is installed on your system, mpmath will automatically detect it and transparently use gmpy integers intead".

Since gmpy is obsolete and has problems installing, might I recommend that you reference gymp2 in the documents?  This will help out people using gympy for the first time with mpmath.

**Comment by skirpichev** [comment] 2024-10-25 02:50
duplicate of https://github.com/mpmath/mpmath/issues/840

**Closed by skirpichev** 2024-10-25 02:50 UTC
