### ISSUE TITLE
findroot bisect solver gives invalid solutions near endpoints

### ISSUE THREAD

**Issue by asmeurer** [mpmath/mpmath#338] opened 2016-12-06 20:41 UTC
This issue has come up with SymPy's nsolve, but it's an issue in findroot, as shown below (I'm using SymPy's lambdify to create the expression, as nsolve does)

```py
from sympy import S, lambdify, symbols
t = symbols('t')
D = S("(10/(t - 1) - (10*t + 10)/(t - 1)**2)*exp((10*t + 10)/(t - 1)) - (-0.011109949473020816773*t**13 - 0.10498117392496721903*t**12 - 0.4662693207692269047*t**11 - 1.2944463271987387573*t**10 - 2.560791476062548363*t**9 - 3.7445986907826045347*t**8 - 4.6175581668981299287*t**7 - 3.9202376055011740667*t**6 - 4.1853692405031723697*t**5 - 1.2730163279308121306*t**4 - 2.6093036740226881464*t**3 + 0.37572825889837415047*t**2 - 0.84260381473372911342*t + 0.11395040244406088625)*(0.0011012754893812472661*t**14 - 0.010681747521049671358*t**13 + 0.047852308718456039572*t**12 - 0.13125412233037760452*t**11 + 0.24631294936212648611*t**10 - 0.33462134384239723802*t**9 + 0.3394635962011490975*t**8 - 0.2613214567551016616*t**7 + 0.15344584617039959246*t**6 - 0.068417469219647235265*t**5 + 0.022810045726230519721*t**4 - 0.0055160290938826628221*t**3 + 0.00091495897212439435512*t**2 - 0.00009321390565315082022*t + 4.402028268659469097e-6)/(0.00079356781950148691235*t**14 + 0.0080754749173051706947*t**13 + 0.038855776730768908725*t**12 + 0.11767693883624897794*t**11 + 0.2560791476062548363*t**10 + 0.41606652119806717052*t**9 + 0.57719477086226624108*t**8 + 0.56003394364302486668*t**7 + 0.69756154008386206162*t**6 + 0.25460326558616242613*t**5 + 0.65232591850567203661*t**4 - 0.12524275296612471682*t**3 + 0.42130190736686455671*t**2 - 0.11395040244406088625*t + 0.096961125131689425859)**2 - (0.015417856851337461725*t**13 - 0.13886271777364572765*t**12 + 0.57422770462147247487*t**11 - 1.4437953456341536497*t**10 + 2.4631294936212648611*t**9 - 3.0115920945815751422*t**8 + 2.71570876960919278*t**7 - 1.8292501972857116312*t**6 + 0.92067507702239755476*t**5 - 0.34208734609823617633*t**4 + 0.091240182904922078882*t**3 - 0.016548087281647988466*t**2 + 0.0018299179442487887102*t - 0.00009321390565315082022)/(0.00079356781950148691235*t**14 + 0.0080754749173051706947*t**13 + 0.038855776730768908725*t**12 + 0.11767693883624897794*t**11 + 0.2560791476062548363*t**10 + 0.41606652119806717052*t**9 + 0.57719477086226624108*t**8 + 0.56003394364302486668*t**7 + 0.69756154008386206162*t**6 + 0.25460326558616242613*t**5 + 0.65232591850567203661*t**4 - 0.12524275296612471682*t**3 + 0.42130190736686455671*t**2 - 0.11395040244406088625*t + 0.096961125131689425859)")

import mpmath
mpmath.mp.dps = 20
f = lambdify(t, D, 'mpmath')
sol = mpmath.findroot(f, [-5.00000000069889e-07, 0.019999489999999787], solver='bisect')
```

The answer is `mpf('-5.0000000006988898295997e-7')`. However, `f(sol)` gives `mpf('-2.6047941157827298767758e-13')`. 

I've had many other instances where the solution given is wrong, and not even in the interval (the above is unique in that it actually is in the interval, barely):

```py
sol = mpmath.findroot(f, [0.57999921, 0.5999991999999998] , solver='bisect')
```

gives

```py
mpf('0.57999920999999998727503')
```

(not in the interval)

`f(sol)` is `mpf('7.4500761232698483305748e-13')`

If I set the `tol` to something like `10**-(2*20)` the fake solutions don't get returned (and it doesn't appear to exclude any of the correct ones). But I thought the correct tolerance was supposed to be set automatically for the current precision. 

@scopatz

**Comment by skirpichev** [comment] 2024-02-23 06:37
closed in favor of #339

**Closed by skirpichev** 2024-02-23 06:37 UTC

**Comment by asmeurer** [comment] 2024-02-23 09:04
Are you sure that's the same issue?

**Comment by skirpichev** [comment] 2024-02-23 09:31
Hmm, probably you are right, maybe it worth to keep this separate.  Both are about automatic tuning of parameters for this specific solver.

On another hand, I appreciate more info:
> I've had many other instances where the solution given is wrong, and not even in the interval

In your example the number actually *is* in the specified interval:
```
In [23]: mpmath.mp.dps
Out[23]: 20

In [24]: mpmath.mp.mpf(0.57999921) <= mpmath.mp.mpf('0.57999920999999998727503') <= mpmath.mp.mpf(0.5999991999999998)
Out[24]: True
```

**Comment by skirpichev** [comment] 2024-02-23 13:42
Attached code could reproduce issue using mpmath-only functions: [a.py.txt](https://github.com/mpmath/mpmath/files/14385774/a.py.txt)
I would appreciate a simpler variant, however;)

To me this looks like an enhancement requests, not a bug.  Unless you have a real example, where solution is outside of the interval.  Your second example seems to be an instance of #677.

**Comment by skirpichev** [comment] 2026-06-07 01:27
@asmeurer, note that in your examples functions have *same* sign on interval endpoints:
```pycon
In [1]: t = symbols('t')
   ...: D = S("(10/(t - 1) - (10*t + 10)/(t - 1)**2)*exp((10*t + 10)/(t - 1)) - (-0.011109949473020816773*t**13 - 0.10498117392496721903*t**12 
      ⋮ - 0.4662693207692269047*t**11 - 1.2944463271987387573*t**10 - 2.560791476062548363*t**9 - 3.7445986907826045347*t**8 - 4.61755816689812
      ⋮ 99287*t**7 - 3.9202376055011740667*t**6 - 4.1853692405031723697*t**5 - 1.2730163279308121306*t**4 - 2.6093036740226881464*t**3 + 0.3757
      ⋮ 2825889837415047*t**2 - 0.84260381473372911342*t + 0.11395040244406088625)*(0.0011012754893812472661*t**14 - 0.010681747521049671358*t*
      ⋮ *13 + 0.047852308718456039572*t**12 - 0.13125412233037760452*t**11 + 0.24631294936212648611*t**10 - 0.33462134384239723802*t**9 + 0.339
      ⋮ 4635962011490975*t**8 - 0.2613214567551016616*t**7 + 0.15344584617039959246*t**6 - 0.068417469219647235265*t**5 + 0.0228100457262305197
      ⋮ 21*t**4 - 0.0055160290938826628221*t**3 + 0.00091495897212439435512*t**2 - 0.00009321390565315082022*t + 4.402028268659469097e-6)/(0.00
      ⋮ 079356781950148691235*t**14 + 0.0080754749173051706947*t**13 + 0.038855776730768908725*t**12 + 0.11767693883624897794*t**11 + 0.2560791
      ⋮ 476062548363*t**10 + 0.41606652119806717052*t**9 + 0.57719477086226624108*t**8 + 0.56003394364302486668*t**7 + 0.69756154008386206162*t
      ⋮ **6 + 0.25460326558616242613*t**5 + 0.65232591850567203661*t**4 - 0.12524275296612471682*t**3 + 0.42130190736686455671*t**2 - 0.1139504
      ⋮ 0244406088625*t + 0.096961125131689425859)**2 - (0.015417856851337461725*t**13 - 0.13886271777364572765*t**12 + 0.57422770462147247487*
      ⋮ t**11 - 1.4437953456341536497*t**10 + 2.4631294936212648611*t**9 - 3.0115920945815751422*t**8 + 2.71570876960919278*t**7 - 1.8292501972
      ⋮ 857116312*t**6 + 0.92067507702239755476*t**5 - 0.34208734609823617633*t**4 + 0.091240182904922078882*t**3 - 0.016548087281647988466*t**
      ⋮ 2 + 0.0018299179442487887102*t - 0.00009321390565315082022)/(0.00079356781950148691235*t**14 + 0.0080754749173051706947*t**13 + 0.03885
      ⋮ 5776730768908725*t**12 + 0.11767693883624897794*t**11 + 0.2560791476062548363*t**10 + 0.41606652119806717052*t**9 + 0.57719477086226624
      ⋮ 108*t**8 + 0.56003394364302486668*t**7 + 0.69756154008386206162*t**6 + 0.25460326558616242613*t**5 + 0.65232591850567203661*t**4 - 0.12
      ⋮ 524275296612471682*t**3 + 0.42130190736686455671*t**2 - 0.11395040244406088625*t + 0.096961125131689425859)")
   ...: 
   ...: import mpmath
   ...: mpmath.mp.dps = 20
   ...: f = lambdify(t, D, 'mpmath')
   ...: 

In [2]: f
Out[2]: <function _lambdifygenerated(t)>

In [3]: f(mpmath.mpf(-5.00000000069889e-07))
Out[3]: mpf('-2.6047941157827298767758e-13')

In [4]: f(mpmath.mpf(0.019999489999999787))
Out[4]: mpf('-5.8321601399642075362273e-13')

In [6]: mpmath.mpf(-5.00000000069889e-07) <= sol <= mpmath.mpf(0.019999489999999787)
Out[6]: True

In [7]: sol = mpmath.findroot(f, [0.57999921, 0.5999991999999998] , solver='bisect')

In [8]: mpmath.mpf(0.57999921) <= sol <= mpmath.mpf(0.5999991999999998)
Out[8]: True

In [9]: f(mpmath.mpf(0.57999921)), f(mpmath.mpf(0.5999991999999998))
Out[9]: (mpf('7.4500761232698483305748e-13'), mpf('1.4141443754311016538401e-12'))
```

It's natural to have odd behavior with such inputs.  Same if you will have multiple roots in the interval.  This all documented limitations of the bisect method, common with other interval-based solvers.

Note, that with e10416f9 - ValueError will be raised.  Strictly speaking, it's a breaking change.  But I treat it as a bugfix: we must validate solver's assumptions.

CC @oscarbenjamin, let me know if you would like to restore old behavior.  In this case I don't see other options but close this as wontfix.
