### ISSUE TITLE
AssertionError on mpmath.runtests()

### ISSUE THREAD

**Issue by Keneth-Garcia** [mpmath/mpmath#544] opened 2020-06-22 19:44 UTC
I recently installed Mpmath 1.1.0 on Python 3.8.3. I follow the instructions and run the mpmath.runtests() and all work fine except for testquad, the problem is:
```
> test_quad
    basic_integrals           ok        0.6461758 s
    complex_integration       ok        0.0013039 s
    double_1                  ok        0.1096764 s
    double_2                  ok        0.2130465 s
    double_3                  ok        0.2557877 s
    double_4                  ok        0.1146773 s
    double_5                  ok        0.0830822 s
    double_6                  ok        0.4477933 s
    double_7                  ok        2.1835598 s
    double_trivial            ok        0.0166782 s
    expmath_fail              
TEST FAILED!
ok        0.0133552 s
expmath_integrals         Traceback (most recent call last):
  File "C:\Users\<name>\AppData\Roaming\Python\Python38\site-packages\mpmath\tests\runtests.py", line 118, in testit
    module.__dict__[f]()
  File "C:\Users\<name>\AppData\Roaming\Python\Python38\site-packages\mpmath\tests\test_quad.py", line 88, in test_expmath_fail
    assert ae(quadts(lambda x: sqrt(tan(x)), [0, pi/2]),          pi*sqrt(2)/2)
AssertionError
ok        0.4116084 s
    quad_infinite_mirror      ok        0.0145721 s
    quad_symmetry             ok        0.0005973 s
    quadgl_linear             ok        0.0000974 s
    quadosc                   ok        0.2591071 s
```
What do i need to do for solve this problem? Thanks

Edit: fix formatting // @skirpichev

**Comment by skirpichev** [comment] 2023-04-07 06:21
You should use pytest to run tests, see docs.

Duplicate of #579...

**Closed by skirpichev** 2023-04-07 06:21 UTC
Labels: duplicate
