### ISSUE TITLE
algorithms behind mpmath

### ISSUE THREAD

**Issue by aldazero** [mpmath/mpmath#631] opened 2022-05-31 21:30 UTC
Hello and thanks for this cool library. Can you please let me know where can I find the algorithms behind this library? Is there any documentation for that or I should look at the source code for individual operations?

**Comment by MartinMikkelsen** [comment] 2022-06-21 16:35
Hi, is this what you are looking for?
[Documentation, Mathematical functions](https://mpmath.org/doc/current/functions/index.html)

**Comment by aldazero** [comment] 2022-06-22 18:51
Not really. I am looking for the algorithms and their time complexity. For example, how do you implement mpmath.exp function with arbitrary precision?

**Comment by skirpichev** [comment] 2023-04-19 03:29
Some references are listed on https://mpmath.org/doc/current/references.html  Of course, we could do better...

I'll close this as a duplicate of #224

**Closed by skirpichev** 2023-04-19 03:29 UTC
Labels: duplicate
