### ISSUE TITLE
mp.atan(z).real and fp.atan(z).real use inconsistent sign choices when z.real < -1 and z.imag==0

### ISSUE THREAD

**Issue by pearu** [mpmath/mpmath#865] opened 2024-09-12 07:47 UTC
As in the title.

Reproducer:
```python
>>> mpmath.mp.atan(mpmath.mpc(0, -2))
mpc(real='-1.5707963267948966', imag='-0.54930614433405489')
>>> mpmath.fp.atan(mpmath.mpc(0, -2))
(1.5707963267948966-0.5493061443340549j)
>>> mpmath.__version__
'1.4.0a1.dev43+g0d287bf'
```

Expected result:
```python
>>> import numpy
>>> numpy.arctan(complex(0, -2))
(1.5707963267948966-0.5493061443340549j)
```

**Comment by skirpichev** [comment] 2024-09-12 08:13
No, it's not a bug, because the mp context lacks signed zero (see https://github.com/mpmath/mpmath/issues/167).  Notice, that on another side of the branch cut:
```pycon
>>> fp.atan(fp.mpc(-0.0, -2))  # *that* sign pick up the mpmath
(-1.5707963267948966-0.5493061443340549j)
```
The mpmath choose CCW continuity, just like the Mathematica:
```
In[2]:= ArcTan[-2 I]//N

Out[2]= -1.5708 - 0.549306 I
```

This might be revisited when we decide on #167.  But meanwhile I'll close this as invalid.

**Closed by skirpichev** 2024-09-12 08:13 UTC
Labels: invalid
