### ISSUE TITLE
Inaccurate output from ellippi in 1.2.1

### ISSUE THREAD

**Issue by oscarbenjamin** [mpmath/mpmath#571] opened 2021-02-10 22:31 UTC
Related sympy issue: https://github.com/sympy/sympy/issues/20933
Bisected to mpmath commit b80b8661b6250237cc66de59f37299ea211f3298

The output of ellippi has changed and seems to have become less accurate in mpmath 1.2.1. I'm not sure what to test against for accuracy but the previous version at least was more internally consistent in the associated sympy test for numerical differentiation.

Test script:
```python
from mpmath import ellippi

res = ellippi(2.1 + 0.94j, 2.3 + 0.98j, 2.5 + 0.01j)

print(res)
```
With mpmath 1.1.0 that gives:
```console
$ python test2.py 
(-0.40652414240812 + 2.15476594614048j)
```
With mpmath 1.2.1 that gives:
```console
$ python test2.py 
(-0.41974219158245 + 2.16763486193693j)
```

**Comment by asmeurer** [comment] 2021-02-10 23:55
Wolfram gives a wildly different answer, although I can't tell if it's just a difference in definition. https://www.wolframalpha.com/input/?i=EllipticPi%5B2.1+%2B+0.94+I%2C+2.3+%2B+0.98+I%2C+2.5+%2B+0.01+I%5D

**Comment by skirpichev** [comment] 2021-02-11 04:54
Hmm, recent Mathematica shows me v1.1.0-like answer:
```
$ wolframscript 
Wolfram Language 12.2.0 Engine for Linux x86 (64-bit)
Copyright 1988-2021 Wolfram Research, Inc.

In[1]:= EllipticPi[2.1 + 0.94 I, 2.3 + 0.98 I, 2.5 + 0.01 I]

Out[1]= -0.406524 + 2.15477 I
```

**Comment by fredrik-johansson** [comment] 2021-02-13 07:56
The problem with the old algorithm is that it sometimes gives wrong branch cuts, though it happens to work in this example. Unfortunately, there is no explicit description of the set of inputs for which the old algorithm is correct (nothing published, anyway).

I believe that the poor accuracy with the new algorithm results from inaccurate numerical integration, so it could be fixed by implementing a better numerical integration algorithm in mpmath.

A quicker fix is possible: `elliprj` now takes an optional `integration` flag which selects between the old and new algorithms. We could allow `ellippi` to forward this flag, allowing the user to choose.

**Comment by skirpichev** [comment] 2021-02-13 10:12
> We could allow ellippi to forward this flag, allowing the user to choose.

How the user, esp. a brainless CAS system, should choose the flag, given that "there is no explicit description of the set of inputs for which the old algorithm is correct"?  The only way I see so far - always use integration=0 argument, to restore old behavior.  (This was, actually, may first attempt to workaround issue in the Diofant, stopped as `elliprj` doesn't pass `integration` flag yet.)

Personally, I would suggest reverting back the problem commit (with a related one) to keep a backward compatibility.  Yes, this commit - fix things, but it breaks too.  Or `integration=0` may be set as a default.

**Comment by asmeurer** [comment] 2021-02-15 23:05
What's the best way to tell if a given answer is actually correct? Is there a more naive but slower method that can be used to compare against, or some identity that ellippi should satisfy that can be checked?

**Comment by jksuom** [comment] 2021-02-21 14:16
> the poor accuracy with the new algorithm results from inaccurate numerical integration,

This seems to be the issue. That can be seen by raising the precision:
```
>>> m, z, n = 2.1 + 0.94j, 2.3 + 0.98j, 2.5 + 0.01j
>>> ellippi(m, z, n)
mpc(real='-0.41974219158244985', imag='2.1676348619369326')
>>> ellippi(m, z - pi, n) + 2*ellippi(m, n)
mpc(real='-0.41974219158244985', imag='2.167634861936933')
>>> ellippi(m, z - pi, n)
mpc(real='0.059133365955952928', imag='0.59966498395719148')
>>> ellippi(m, n)
mpc(real='-0.23943777876920139', imag='0.78398493898987076')
>>> mp.dps
15
>>> mp.dps = 30
>>> ellippi(m, z, n)
mpc(real='-0.407212439838793996529397272726887', imag='2.15542979763493136069774659445483')
>>> ellippi(m, z - pi, n)
mpc(real='0.0591333659559529409277470851710119', imag='0.599664983957191477832052503134185')
>>> ellippi(m, n)
mpc(real='-0.233172902897373468728571481821314', imag='0.777882406838869941432849392439574')
```
The real part of `z` is between `pi/2` and `3*pi/2`. Hence the quasi-periodic `ellippi(m, z, n)` will be computed as `ellippi(m, z - pi, n) + 2*ellippi(m, n)`, where the real part of `z - pi` is in the domain `[-pi/2, pi/2]` of the principal branch. The pole of the complete integral `ellippi(m, n)` at `sin(phi) = sqrt(1/n) = 0.63 - 0.0013j` is very close to the integration path `0 <= sin(phi) <= 1` creating a singularity in the integrand. A corresponding singularity will also appear in `elliprj` making its integral inaccurate (when `integration > 0`).

**Comment by fredrik-johansson** [comment] 2021-02-26 12:08
I added an adaptive `quadsubdiv` function that solves this problem. Its efficiency can be improved. It would be even better to make `quad` itself subdivision-adaptive, but that would require some testing to make sure existing applications don't regress too much.

**Comment by fredrik-johansson** [comment] 2021-02-26 14:50
Supporting the integration=0 fallback would still be useful since the integration algorithm is significantly slower (and will remain slower even if `quadsubdiv` is optimized).

**Comment by skirpichev** [comment] 2021-02-27 05:07
> I added an adaptive quadsubdiv function that solves this problem. 

Seems to be a good workaround so far.  What about minor release?  So far, SymPy people skipped the affected test, I also have seen related failures in the Diofant CI (more often than something else, i.e. timeouts).

> Supporting the integration=0 fallback would still be useful since the integration algorithm is significantly slower

Does it matter, if without integration=nonzero - the algorithm is not correct?  It's still not clear for me how e.g. CAS should choose the correct `integration` value.  And why this can't be doable on the mpmath's level.

**Comment by fredrik-johansson** [comment] 2021-03-01 16:22
> Seems to be a good workaround so far. What about minor release?

Let's wait a few days.

> Does it matter, if without integration=nonzero - the algorithm is not correct? It's still not clear for me how e.g. CAS should choose the correct integration value. And why this can't be doable on the mpmath's level.

There are two algorithms:

A (the old algorithm) - faster, sometimes correct
B (the new algorithm) - slower, always correct

The problem is that there is no easy way to determine where algorithm A is valid. ellippi is a function of three complex variables (the underlying elliprj function is a complex of four complex variables), and the correct region is some subset of C^3 (or C^4) with nonlinear boundaries that I have no idea how to compute. In this scenario, I prefer to choose the algorithm that always works.

The general problem of how a CAS should choose between two such algorithms A and B has no easy answer; it depends on priorities.

**Comment by skirpichev** [comment] 2021-03-01 16:51
On Mon, Mar 01, 2021 at 08:22:54AM -0800, Fredrik Johansson wrote:
>    Let's wait a few days.

(Diofant can't offer much testing in few days.  Maybe SymPy people can
re-enable failing tests.)

BTW, maybe few other may be relevant for the next minor release,
ex. #574.  And #565 is still open.

>    There are two algorithms:
>    A (the old algorithm) - faster, sometimes correct
>    B (the new algorithm) - slower, always correct

I'm was in impression that being correct - the case for mp-math.

>    The general problem of how a CAS should choose between two such algorithms
>    A and B has no easy answer; it depends on priorities.

The priority of any CAS is clear.  Either return a valid answer - on
nothing (unevaluated expression, error, and so on).

**Comment by skirpichev** [comment] 2023-04-28 10:49
Ok, now integration=1 per default.  Also, regression test was added in 7123a67a

**Closed by skirpichev** 2023-04-28 10:49 UTC
